config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'camps#index'
  
  devise_for :users,
   :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :camps, :path => 'aktiviteter' do
    resources :images
    post 'camps/:id/join' => 'camps#join'
    patch 'camps/:id/update_grants' => 'camps#update_grants'
    patch 'camps/:id/toggle_granting' => 'camps#toggle_granting'
  end

  get '/chronicles' => 'chronicles#index'

end

app/models/camp.rb
class Camp < ActiveRecord::Base
	belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

	has_many :memberships
	has_many :users, through: :memberships
  has_many :images #, :dependent => :destroy

	validates :creator, presence: true
	validates :name, presence: true
	validates :subtitle, presence: true
	validates :contact_email, presence: true
	validates :contact_name, presence: true
	validates :accept_terms, acceptance: { accept: true }

	filterrific(
	default_filter_params: { sorted_by: 'updated_at_desc' },
	available_filters: [
	  :sorted_by,
	  :search_query,
	  :not_fully_funded,
	  :not_min_funded,
	  :not_seeking_funding,
      :is_current_event
	]
	)
	# Scope definitions. We implement all Filterrific filters through ActiveRecord
	# scopes. In this example we omit the implementation of the scopes for brevity.
	# Please see 'Scope patterns' for scope implementation details.
	  scope :search_query, lambda { |query|
	    return nil  if query.blank?
	    # condition query, parse into individual keywords
	    terms = query.downcase.split(/\s+/)
	    # replace "*" with "%" for wildcard searches,
	    # append '%', remove duplicate '%'s
	    terms = terms.map { |e|
	      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
	    }
	    # configure number of OR conditions for provision
	    # of interpolation arguments. Adjust this if you
	    # change the number of OR conditions.
	    num_or_conditions = 2
	    where(
	      terms.map {
	        or_clauses = [
	          "LOWER(camps.name) LIKE ?",
	          "LOWER(camps.subtitle) LIKE ?"
	        ].join(' OR ')
	        "(#{ or_clauses })"
	      }.join(' AND '),
	      *terms.map { |e| [e] * num_or_conditions }.flatten
	    )
	  }

	scope :sorted_by, lambda { |sort_option|
	    # extract the sort direction from the param value.
	    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'

	    case sort_option.to_s
	    when /^name/
	       # Simple sort on the created_at column.
	       # Make sure to include the table name to avoid ambiguous column names.
	       # Joining on other tables is quite common in Filterrific, and almost
	       # every ActiveRecord table has a 'created_at' column.
	       order("camps.name #{ direction }")
	    when /^updated_at_/
	       order("camps.updated_at #{ direction }")
	    when /^created_at_/
	       order("camps.created_at #{ direction }")
	       raise(ArgumentError, "Sort option: #{ sort_option.inspect }")
	    else
	       raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
	    end
	}

	scope :not_fully_funded, lambda { |flag|
		return nil  if '0' == flag # checkbox unchecked
		where(fullyfunded: false)
	}

	scope :not_min_funded, lambda { |flag|
		return nil  if '0' == flag # checkbox unchecked
		where(minfunded: false)
	}

	scope :not_seeking_funding, lambda { |flag|
		return nil  if '0' == flag # checkbox unchecked
		where(grantingtoggle: true)
	}

	  scope :is_current_event, lambda { |flag|
	    where(camps: { event_id: Rails.application.config.default_event })
	  }

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    filter = params[:filterrific] || { sorted_by: 'updated_at_desc' }
    filter[:active] = true
    filter[:not_hidden] = true
    filter[:is_current_event] = true
    if (!current_user.nil? && (current_user.admin? || current_user.guide?))
      filter[:hidden] = true
      filter[:not_hidden] = false
    end

    @filterrific = initialize_filterrific(
      Camp,
      filter
    ) or return
    @camps = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @camp = Camp.new
    @camps = Camp.all
    @submit_text = 'Skapa'
  end

  def edit
    @camp = Camp.find params[:id]
    @camps = Camp.all
    @submit_text = 'Uppdatera'
  end

  def create
    @camp = Camp.new(camp_params)
    @camp.creator = current_user

    if @camp.save
      redirect_to camp_path(@camp)
    else
      flash.now[:notice] = "Errors: #{@camp.errors.full_messages.join(', ')}"
      render :new
    end
  end

  # Toggle granting

  def toggle_granting
    @camp = Camp.find(params[:id])
    @camp.toggle!(:grantingtoggle)
    redirect_to camp_path(@camp)
  end

  # Handle the grant updates in their own controller action
  def update_grants
    @camp = Camp.find(params[:id])

    # Reduce the number of grants assigned to the current user by the number
    # of grants given away. Increase the number of grants assigned to the
    # camp by the same number of grants.

    # Decrement user grants. Check first if granting more than needed.
    granted = params['grants'].to_i
    if @camp.grants_received + granted > @camp.maxbudget
      granted = @camp.maxbudget - @camp.grants_received
    end
    current_user.grants -= granted

    # Increase camp grants.
    @camp.grants_received += granted

    if @camp.grants_received >= @camp.minbudget
      @camp.minfunded = true
    else
      @camp.minfunded = false
    end

    if @camp.grants_received >= @camp.maxbudget
      @camp.fullyfunded = true
    else
      @camp.fullyfunded = false
    end

    unless current_user.save
      flash[:notice] = "Errors: #{current_user.errors.full_messages.join(', ')}"
      redirect_to camp_path(@camp) and return
    end

    unless @camp.save
      flash[:notice] = "Errors: #{@camp.errors.full_messages.join(', ')}"
      redirect_to camp_path(@camp) and return
    end

    redirect_to camp_path(@camp)
    flash[:notice] = "Thanks for sending #{granted} grant(s)"
  end

  def update
    @camp = Camp.find(params[:id])

    if @camp.update_attributes camp_params
      redirect_to camp_path(@camp)
    else
      flash.now[:notice] = "Errors: #{@camp.errors.full_messages.join(', ')}"
      render :edit
    end
  end

  def destroy
    @camp = Camp.find(params[:id])
    @camp.destroy!

    redirect_to camps_path
  end

  # Display a camp and its users
  def show
    @camp = Camp.find(params[:id])
    @users = @camp.users

    # Added this to move some code out of the view.
    if current_user
      @user_grant_limit = current_user.grants
    end
  end

  # Allow a user to join a particular camp.
  def join
    @camp = Camp.find(params[:id])

    params[:user] ? @user = User.find(params[:user]) : @user = nil

    #
    # Only add a user to the list of associated members if the user isn't
    # in the list. We should add a uniqueness validation to this.
    #

    if !@user
      flash[:notice] = "Du måste vara inloggad."
    elsif @camp.users.include?(@user)
      flash[:notice] = "Nice! You've already sent your email to the creator."
    else
      flash[:notice] = "Sweet! You just sent your email adress to the creator."
      @camp.users << @user
    end
    redirect_to @camp
  end

  private

  def camp_params
    params.require(:camp).permit!
  end

end

app/views/camps/_form.html.erb
<%= form_for @camp do |form| %>

<div class="header-heading">
  <%= t("form_basics_headline") %>
</div>

<p>Kul att du vill bidra med en aktivitet till Kungsholmstorgs Dag! Fyll i formuläret nedan så gott du kan, du kan alltid uppdatera senare. När du är klar med formuläret kan du ladda upp bilder på aktiviteten och er som arrangerar. Vi granskar alla aktiviteter innan de publiceras för att säkerställa att den bidrar till generositet, glädje och nya möten.</p>

<% if Rails.configuration.x.firestarter_settings["placement"] %>

  <div class="header-heading">
    <%= t("form_location_headline") %>
  </div>

  <div>
    <div id="map"></div>
  </div>

<% end %>

  <div class="combo" id="name">
    <%= form.label t("form_dream_name_label") %>
    <%= form.text_field :name, :maxlength => 64 %>
    <%= t("form_dream_name_guidetext_html") %>
  </div>

  <div class="combo" id="subtitle">
    <%= form.label t("form_subtitle_label") %>
    <%= form.text_area :subtitle, :maxlength => 255 %>
    <%= t("form_subtitle_guidetext_html") %>
  </div>

  <div class="combo" id="address">
    <%= form.label t("form_address_label") %>
    <%= form.text_field :address, :maxlength => 255 %>
  </div>

  <div class="combo" id="start_time">
    <%= form.label t("form_start_time_label") %>
    <%= form.text_field :start_time, :maxlength => 255 %>
  </div>

  <!-- div class="combo" id="end_time">
    <%= form.label t("form_end_time_label") %>
    <%= form.text_field :end_time, :maxlength => 64 %>
  </div -->

  <div class="combo" id="organizer">
    <%= form.label t("form_organizer_label") %>
    <%= form.text_field :organizer, :maxlength => 64 %>
    <%= t("form_organizer_guidetext_html") %>
  </div>

  <div class="combo" id="contact_name">
    <%= form.label t("form_creator_name_label") %>
    <%= form.text_field :contact_name, :maxlength => 64 %>
    <%= t("form_creator_name_guidetext_html") %>
  </div>

  <div class="combo" id="contact_email">
    <%= form.label t("form_creator_email_label") %>
    <%= form.text_field :contact_email, :maxlength => 64 %>
    <%= t("form_creator_email_guidetext_html") %>
  </div>

  <div class="combo" id="contact_phone"></div>
  <% if Rails.configuration.x.firestarter_settings["contact_phone"] %>
    <%= form.label t("form_contact_phone_label") %>
    <%= form.text_field :contact_phone, :maxlength => 64 %>
    <%= t("form_contact_phone_guidetext_html") %>
  <% end %>

  <% 2.times do %>
    <br/>
  <% end %>

  <div class="hidden">
    <%= form.text_field :latitude, :maxlength => 64, id: 'latitude' %>
  </div>

  <div class="hidden">
    <%= form.text_field :longitude, :maxlength => 64, id: 'longitude'  %>
  </div>

  <% if Rails.configuration.x.firestarter_settings["additional_info"] %>
    <div class="header-heading">
      <%= t("form_additional_headline") %>
    </div>
  <% end %>

  <div class="combo" id="additonal"></div>
  <% if Rails.configuration.x.firestarter_settings["additional_info"] %>
    <%= t("form_additional_info_text_html") %>
  <% end %>

  <div class="combo" id="description"></div>
  <% if Rails.configuration.x.firestarter_settings["description"] %>
    <%= form.label t("form_description_label") %>
    <%= form.text_area :description, :maxlength => 4096 %>
    <%= t("form_description_guidetext_html") %>
  <% end %>

  <div class="combo" id="benefit"></div>
  <% if Rails.configuration.x.firestarter_settings["benefit"] %>
    <%= form.label t("form_benefit_label") %>
    <%= form.text_area :benefit, :maxlength => 4096 %>
    <%= t("form_benefit_guidetext_html") %>
  <% end %>

  <div class="combo" id="electricity"></div>
  <% if Rails.configuration.x.firestarter_settings["electricity"] %>
    <%= form.label t("form_electricity_label") %>
    <%= form.text_field :electricity, :maxlength => 256 %>
    <%= t("form_electricity_guidetext_html") %>
  <% end %>

  <div class="combo" id="light"></div>
  <% if Rails.configuration.x.firestarter_settings["light"] %>
    <%= form.label t("form_light_label") %>
    <%= form.text_field :light, :maxlength => 512 %>
    <%= t("form_light_guidetext_html") %>
  <% end %>

  <div class="combo" id="fire"></div>
  <% if Rails.configuration.x.firestarter_settings["fire"] %>
    <%= form.label t("form_fire_label") %>
    <%= form.text_area :fire, :maxlength => 512 %>
    <%= t("form_fire_guidetext_html") %>
  <% end %>

  <div class="combo" id="noise"></div>
  <% if Rails.configuration.x.firestarter_settings["noise"] %>
    <%= form.label t("form_noise_label") %>
    <%= form.text_field :noise, :maxlength => 256 %>
    <%= t("form_noise_guidetext_html") %>
  <% end %>

  <div class="combo" id="nature"></div>
  <% if Rails.configuration.x.firestarter_settings["nature"] %>
    <%= form.label t("form_nature_label") %>
    <%= form.text_area :nature, :maxlength => 512 %>
    <%= t("form_nature_guidetext_html") %>
  <% end %>

  <div class="combo" id="moop"></div>
  <% if Rails.configuration.x.firestarter_settings["moop"] %>
    <%= form.label t("form_moop_label") %>
    <%= form.text_area :moop, :maxlength => 1024 %>
    <%= t("form_moop_guidetext_html") %>
  <% end %>

  <div class="combo" id="plan"></div>
  <% if Rails.configuration.x.firestarter_settings["plan"] %>
    <%= form.label t("form_plan_label") %>
    <%= form.text_area :plan, :maxlength => 1024 %>
    <%= t("form_plan_guidetext_html") %>
  <% end %>

  <div class="combo" id="cocreation"></div>
  <% if Rails.configuration.x.firestarter_settings["cocreation"] %>
    <%= form.label t("form_cocreation_label") %>
    <%= form.text_area :cocreation, :maxlength => 4096 %>
    <%= t("form_cocreation_guidetext_html") %>
  <% end %>

  <div class="combo" id="neighbors"></div>
  <% if Rails.configuration.x.firestarter_settings["neighbors"] %>
    <%= form.label t("form_neighbors_label") %>
    <%= form.text_area :neighbors, :maxlength => 4096 %>
    <%= t("form_neighbors_guidetext_html") %>
  <% end %>

  <br/>
  <br/>

  <div class="checkbox_container">
    <%= form.check_box :need_electricity, class: 'form_checkbox' %>
    <%= form.label "Jag vill gärna ha tillgång till el om möjligt" %>
  </div>

  <br/>
  <br/>

  <div class="checkbox_container">
    <%= form.check_box :need_tent, class: 'form_checkbox' %>
    <%= form.label "Jag är intresserad av att hyra bord & tält" %>
  </div>

  <% if Rails.configuration.x.firestarter_settings["marketing"] %>
    <br/>
    <br/>
    <div class="header-heading">
      <%= t("form_marketing_headline") %>
    </div>

    <div class="combo" id="marketing">
    <%= form.label t("form_marketing_label") %>
    <%= form.text_area :marketing, :maxlength => 1024 %>
    <%= t("form_marketing_guidetext_html") %>
    </div>

    <div class="combo" id="facebook">
    <%= form.label t("form_facebook_label") %>
    <%= form.text_field :facebook_link, :maxlength => 256 %>
    </div>

    <div class="combo" id="twitter">
    <%= form.label t("form_twitter_label") %>
    <%= form.text_field :twitter_link, :maxlength => 256 %>
    </div>

    <div class="combo" id="instagram">
    <%= form.label t("form_instagram_label") %>
    <%= form.text_field :instagram_link, :maxlength => 256 %>
    </div>

    <div class="combo" id="video">
    <%= form.label t("form_video_label") %>
    <%= form.text_field :video_link, :maxlength => 256 %>
    </div>

  <% end %>

  <% if Rails.configuration.x.firestarter_settings["granting"] %>
    <br/>
    <br/>
    <div class="header-heading">
      <%= t("form_artgrants_headline") %>
    </div>
  <% end %>

  <div class="combo" id="artgrants"></div>

  <% if Rails.configuration.x.firestarter_settings["granting"] %>
    <%= t("form_artgrants_text_html") %>
  <% end %>

  <div class="combo" id="minbudget"></div>
  <% if Rails.configuration.x.firestarter_settings["granting"] %>
    <%= form.label t("form_minigrants_label") %>
    <%= form.number_field :minbudget, :maxlength => 6 %>
    <%= t("form_minigrants_guidetext_html") %>
  <% end %>

  <div class="combo" id="maxbudget"></div>

  <% if Rails.configuration.x.firestarter_settings["granting"] %>
    <%= form.label t("form_maxigrants_label") %>
    <%= form.number_field :maxbudget, :maxlength => 6 %>
    <%= t("form_maxigrants_guidetext_html") %>
  <% end %>

  <div class="combo" id="budgetplan"></div>

  <% if Rails.configuration.x.firestarter_settings["budgetplan"] %>
    <%= form.label t("form_budgetplan_label") %>
    <%= form.text_area :budgetplan, :maxlength => 4096 %>
    <%= t("form_budgetplan_guidetext_html") %>
  <% end %>


  <% if Rails.configuration.x.firestarter_settings["responsibility_check"] %>
    <br/>
    <br/>
    <%= t("form_responsibility_guidetext_html") %>
    <div class="checkbox_container">
      <%= form.check_box :accept_terms, class: 'form_checkbox' %>
      <%= form.label t("form_responsibility_label"), class: 'form_checkbox' %>
    </div>
  <% end %>

  <% if current_user.admin %>
    <br/>
    <br/>
    <b>Publicerat</b>
    <div class="checkbox_container">
      <%= form.check_box :published, class: 'form_checkbox' %>
    </div>
  <% end %>

  <br/>
  <br/>
  <p><em>Behöver du eventuellt söka polistillstånd, maila max.lauritzen@thread.se för att få lite hjälp på traven.</em></p>

  <div class="submit">
    <% if @camp.name %>
      <%= form.submit "Updatera aktivitet", class: 'btn btn-success' %>
    <% else %>
      <%= form.submit "Skapa aktivitet", class: 'btn btn-success' %>
    <% end %>
  </div>

<% end %>

app/views/camps/edit.html.erb
<% content_for(:head) do %>
  <% browser_title = "Editing " + @camp.name + " - " + t(:browser_title_tag) %>
  <title><%= browser_title %></title>
  <%= javascript_include_tag 'gmap_functions' %> 
  <%= javascript_include_tag 'new_camp_map' %> 
<% end %>

<% if current_user && (@camp.creator == current_user || current_user.admin) %>
  <%= render(
    partial: 'camps/form',
  ) %>
<% else %>
    <p class="alert">Only the original creator can edit this page.</p>
<% end %>

app/views/camps/index.js.erb
<%# app/views/camps/index.js.erb %>
<% js = escape_javascript(
  render(partial: 'camps/list', locals: { camps: @camps })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/camps/new.html.erb
<% content_for(:head) do %>
    <% browser_title = t(:browser_title_tag) %>
    <title><%= browser_title %></title>
    <%= javascript_include_tag 'gmap_functions' %> 
    <%= javascript_include_tag 'new_camp_map' %> 
<% end %>

<%= render(
  partial: 'camps/form',
) %>

app/views/camps/show.html.erb
<div class="row">
    <div class="col-md-8">
        <h1 class="header-sub-heading"><%= @camp.name %></h1>
    </div>
</div>

<div class="row">

    <div class="col-md-8">

        <!-- Blueimp Gallery -->
        <div id="blueimp-gallery" class="blueimp-gallery">
            <div class="slides"></div>
            <h3 class="title"></h3>
            <a class="prev">‹</a>
            <a class="next">›</a>
            <a class="close">×</a>
            <a class="play-pause"></a>
            <ol class="indicator"></ol>
        </div>

        <div id="links">
            <% @camp.images.each_with_index do |image, index| %>
                <% status = "" %>
                <% if index == 0 %>
                    <% status = "active" %>
                <% end %>
                <% image_url = image.attachment.url(:original)%>

                <div class="thumbnail">
                    <a href="<%= image_url %>">
                        <img src="<%= image_url %>">
                    </a>
                </div>

            <% end %>

        </div>

        <% content_for(:head) do %>
            <% browser_title = @camp.name + " - " + t(:browser_title_tag) %>
            <title><%= browser_title %></title>
            <%= javascript_include_tag 'blueimp_script' %>
        <% end %>

        <!-- Creation text content -->
        <div class="camp-description">
            <b>Sammanfattning</b>
            <p><%= simple_format(@camp.subtitle) %></p>
        </div>

        <% if Rails.configuration.x.firestarter_settings["description"] and @camp.description != "" %>
            <div class="camp-description">
                <b><%=t :form_description_label %></b>
                <p><%= simple_format(@camp.description) %></p>
            </div>
        <% end %>

        <% if Rails.configuration.x.firestarter_settings["benefit"] and @camp.benefit != "" %>
            <div class="camp-description">
                <b><%=t :form_benefit_label %></b>
                <p><%= simple_format(@camp.benefit) %></p>
            </div>
        <% end %>

        <% if Rails.configuration.x.firestarter_settings["plan"] and @camp.plan != "" %>
            <div class="camp-description">
                <b><%=t :form_plan_label %></b>
                <p><%= simple_format(@camp.plan) %></p>
            </div>
        <% end %>

        <% if Rails.configuration.x.firestarter_settings["moop"] and @camp.moop != "" %>
            <div class="camp-description">
                <b><%=t :form_moop_label %></b>
                <p><%= simple_format(@camp.moop) %></p>
            </div>
        <% end %>

        <% if Rails.configuration.x.firestarter_settings["budgetplan"] and @camp.budgetplan != "" %>
            <div class="camp-description">
                <b><%=t :form_budgetplan_label %></b>
                <p><%= simple_format(@camp.budgetplan) %></p>
            </div>
        <% end %>

        <% if Rails.configuration.x.firestarter_settings["cocreation"] and @camp.cocreation != "" %>
            <div class="camp-description">
                <b><%=t :form_cocreation_label %></b>
                <p><%= simple_format(@camp.cocreation) %></p>
            </div>
        <% end %>

    </div> <!-- col-md-8 -->

    <div class="col-md-4">

        <% if !user_signed_in? and Rails.configuration.x.firestarter_settings["creation_sidebar_welcome"] %>
            <div class="panel panel-default">
                <div class="panel-heading"><%=t :what_is_this_title %></div>
                <div class="panel-body">
                    <p><%=t :what_is_this_text_html %></p>
                </div>
            </div>
        <% end %>

        <% random = Camp.order("RANDOM()").first %>
        <a href="<%= url_for(random) %>" class="btn btn-primary camp-button" role="button">
            Fler aktiviteter <span class="glyphicon glyphicon-random" aria-hidden="true"></span>
        </a>

        <div class="creation-info">
            <ul>

                <li><span><h2 class="header-sub-heading"><%=t :creation_info_headline %></h2></span></li>

                <% if current_user && (@camp.creator == current_user || current_user.admin) %>
                    <li><span>
                        <a href="<%= edit_camp_path(@camp) %>" class="btn btn-primary camp-button" role="btn button">Updatera aktivitet</a>
                    </li></span>
                    <li><span>
                        <a href="<%= camp_images_path(@camp) %>" class="btn btn-primary camp-button" role="btn button">Ladda upp bilder</a>
                    </li></span>
                <% end %>

                <br>

                <li><span><b>Kontaktperson:</b>  <br> <%= @camp.contact_name %></span></li>
                <br>

                <% if Rails.configuration.x.firestarter_settings["organizer"] and @camp.organizer != "" %>
                    <li><div><b>Arrangeras av:</b>  <br> <%= @camp.organizer %></div></li>
                    <br>
                <% end %>


                <li><span><b>Mail:</b>  <br> <%= @camp.contact_email %></span></li>
                 <br>

                <% if Rails.configuration.x.firestarter_settings["address"] and  @camp.address != "" %>
                    <li><div>
                        <b><%=t :form_address_label %></b> <br> <%= @camp.address %>
                    </div></li>


                    <br>
                <% end %>


                <% if Rails.configuration.x.firestarter_settings["time"] and  @camp.start_time != "" %>
                    <li><div>
                        <b><%=t :form_start_time_label %></b>  <br> <%= @camp.start_time %>
                    </div></li>


                    <br>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["marketing"] and @camp.facebook_link != "" %>
                    <div class="camp-description">
                        <% link = @camp.facebook_link %>
                        <% if(link[0,7] != "http://" && link[0,8] != "https://" ) %>
                            <% link = "http://" + link %>
                        <% end %>
                        <p><b><%= link_to("Facebook", link) %></b></p>
                    </div>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["marketing"] and @camp.twitter_link != "" %>
                    <div class="camp-description">
                        <% link = "http://twitter.com/" + @camp.twitter_link %>
                        <p><b><%= link_to("Twitter", link) %></b></p>
                    </div>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["marketing"] and @camp.instagram_link != "" %>
                    <div class="camp-description">
                        <% link = "http://www.instagram.com/" + @camp.instagram_link %>
                        <p><b><%= link_to("Instagram", link) %></b></p>
                    </div>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["marketing"] and @camp.video_link != "" %>
                    <div class="camp-description">
                        <% link = @camp.video_link %>
                        <% if(link[0,7] != "http://" && link[0,8] != "https://" ) %>
                            <% link = "http://" + link %>
                        <% end %>
                        <p><b><%= link_to("Videolänk", link) %></b></p>
                    </div>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["electricity"] and @camp.electricity != "" %>
                    <li><span>
                        <b><%=t :form_electricity_label %></b> <%= @camp.electricity %>
                    </span></li>


                    <br>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["light"] and  @camp.light != "" %>
                    <li><span>
                        <b><%=t :form_light_label %></b> <%= @camp.light %>
                    </span></li>


                    <br>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["fire"] and  @camp.fire != "" %>
                    <li><span>
                        <b><%=t :form_fire_label %></b> <%= @camp.fire %>
                    </span></li>


                    <br>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["noise"] and  @camp.noise != "" %>
                    <li><span>
                        <b><%=t :form_noise_label %></b> <%= @camp.noise %>
                    </span></li>


                    <br>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["nature"] and  @camp.nature != "" %>
                    <li><span>
                        <b><%=t :form_nature_label %></b> <%= @camp.nature %>
                    </span></li>


                    <br>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["grants"] and  @camp.minbudget != "" %>
                    <li><span>
                        <b><%=t :form_minigrants_label %></b> <%= @camp.minbudget %>
                    </span></li>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["grants"] and  @camp.maxbudget != "" %>
                    <li><span>
                        <b><%=t :form_maxigrants_label %></b> <%= @camp.maxbudget %>
                    </span></li>


                    <br>
                <% end %>

                <% if Rails.configuration.x.firestarter_settings["add_to_list"] %>
                    <br>
                    <% if @camp.creator != current_user %>
                        <li><b><%=t :cocreator_application_guidetext %></b></li>
                        <div class="join_creation">
                            <%= button_to "Add my name", {action: "join", user: current_user }, {class: 'btn btn-success button'} %>
                        </div>
                    <% end %>

                    <% if current_user && (@camp.creator == current_user || current_user.guide) %>
                        <br>
                        <li><span><b><%=t :cocreators_list_guidetext %></b>
                            <% @users.each do |user| %>
                                <%= user.email %><br>
                            <% end %>
                        </span></li>
                    <% end %>
                <% end %>

                <% if current_user && (@camp.creator == current_user || current_user.admin) %>
                    <%= form_for @camp, method: :delete do |f| %>
                        <%= f.submit 'Ta bort aktiviteten', class: "btn btn-danger" , data: { confirm: 'Är du säker på att du vill ta bort aktiviteten?' } %>
                    <% end %>
                <% end %>

            </ul>

        </div> <!-- creation-info -->

    </div> <!-- col-md-3 -->

</div> <!-- row -->