config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'camps#index'
  
  devise_for :users,
   :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :camps, :path => 'aktiviteter' do
    resources :images
    post 'camps/:id/join' => 'camps#join'
    patch 'camps/:id/update_grants' => 'camps#update_grants'
    patch 'camps/:id/toggle_granting' => 'camps#toggle_granting'
  end

  get '/chronicles' => 'chronicles#index'

end

app/views/shared/_header.html.erb
<% image_path = image_path("coverphoto.jpg") %>

<header>
<div class="container coverphoto" ">

  <div class="main_content top_menu">
      <div class="row">
        <div class="col-xs-4">
          <h1><a class="header-top-menu" href="/"><%=t :top_headline_html %></a></h1>
        </div>
        <div class="col-xs-8">
          <div class="header-nav">
            <a href="/"><%=t :creations_menu %></a>
            <%= link_to t("chronicles_menu"), chronicles_path %>
            <% if user_signed_in? %>
            <%= link_to t("register_creation_menu"), new_camp_path %>
            <% end %>
            <% if !user_signed_in? %>
            <%= link_to t("login_menu"), new_user_session_path %>
            <% end %>
            <% if !user_signed_in? %>
            <%= link_to t("register_menu"), new_user_registration_path %>
            <% end %>
            <% if user_signed_in? %>
            <%= link_to t("logout_menu"), destroy_user_session_path, method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
  </div>

</div>

</header>