config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'camps#index'
  
  devise_for :users,
   :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :camps, :path => 'aktiviteter' do
    resources :images
    post 'camps/:id/join' => 'camps#join'
    patch 'camps/:id/update_grants' => 'camps#update_grants'
    patch 'camps/:id/toggle_granting' => 'camps#toggle_granting'
  end

  get '/chronicles' => 'chronicles#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  # Add paperclip for S3
  has_attached_file :attachment, {
                      styles: {
                        thumb: '100x100>',
                        square: '200x200#',
                        medium: '300x300>',
                        large: '500x500>'
                      },
                      :convert_options => {
                        :all => "-quality 75 -interlace Plane"
                      }
                    }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_filter :camp_id

  def index
    @images = Image.where(camp_id: @camp_id)
    @camp = Camp.find(@camp_id)
  end

  def show
    image = Image.find_by_id(params[:id])
    #send_data image.image, disposition: :inline
  end

  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id

    if @image.save
      redirect_to camp_images_path(camp_id: @camp_id)
    else
      render action: 'index'
    end
  end

  def destroy
    @image = Image.find_by_id(params[:id])
    @image.attachment = nil
    @image.save!
    @image.destroy!

    redirect_to camp_images_path(camp_id: @camp_id)
  end

  def camp_id
    @camp_id = params[:camp_id]
  end

  def camp
    @camp = Camp.find(params[:id])
  end

  private

  def image_params
    params.permit(:attachment, :camp_id)
  end
end

app/views/images/index.html.erb
<% content_for(:head) do %>
  <% browser_title = "Editing " + @camp.name + " - " + t(:browser_title_tag) %>
  <title><%= browser_title %></title>
<% end %>

<% if current_user && (@camp.creator == current_user || current_user.admin || current_user.guide) %>
    <div class="row">
        <h2 class="header-sub-heading">Activity images</h2>
    </div>

    <div class="row">
        <% @images.each do |image| %>
            <div class="camp-image">
                <% image_url = image.attachment.url(:medium) %>
                <%= image_tag(image_url) %>
                <%= form_for image, url: camp_image_path(image.camp_id, image),  method: :delete do |form| %>
                    <%= form.submit 'Remove image', { class: 'delete_button' } %>
                <% end %>
            </div>
        <% end %>
    </div>

    <div class="row">
        <a href="<%= camp_path(@camp_id) %>" class="btn btn-info camp-button" role="button">Back</a>
    </div>

    <div class="row">
        <h2 class="header-sub-heading camp-upload_image">Upload images</h2>

        <p>Image files must be jpg, png or gif.</p>

    </div>


    <%= form_tag camp_images_path(camp_id: @camp_id), method: :post, multipart: true do %>
        <div class="row">
            <%= label_tag :attachment, 'Upload image' %>
        </div>

        <div class="row">
            <div class="col-md-4">
                <%= file_field_tag :attachment %>
                <%= submit_tag 'Upload', class: 'btn btn-success camp-button' %>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4"></div>
        </div>
    <% end %>
<% else %>
    <p class="alert">Only the original creator can edit this page.</p>
<% end %>